theme: jekyll-theme-cayman

collections:
  posters:
    permalink: '/:title.html'
    output: true

defaults:
  - scope:
      path: '' # an empty string here means all files in the project
      type: 'posters' # previously `post` in Jekyll 2.2.
    values:
      layout: 'A3-poster'

author:
  name: 'Paramdigma'
  category:
    - 'Computational Strategies'
    - 'Parametric Architecture'
  logo: assets/img/logo-inverted.svg
  social:
    - icon: fas fa-home
      account: www.paramdigma.com
    - icon: fab fa-instagram
      account: '@paramdigma'
    - icon: fab fa-twitter
      account: '@paramdigma'
    - icon: far fa-envelope
      account: info@paramdigma.com

background:
  image: assets/img/frances-gunn-57430-unsplash.jpg
  overlay:
    color: black
    opacity: 0.5
